### ISSUE TITLE
Failed to build on Ubuntu 20.04

### ISSUE THREAD

**Issue by penevd** [xmrig/xmrig-cuda#102]
`
make -j$(nproc)
[ 68%] Built target xmrig-cu
make[2]: *** No rule to make target '/usr/local/cuda/lib64/stubs/libcuda.so', needed by 'libxmrig-cuda.so'.  Stop.
make[1]: *** [CMakeFiles/Makefile2:78: CMakeFiles/xmrig-cuda.dir/all] Error 2
make: *** [Makefile:84: all] Error 2
`

**Comment by onemillionbucks** [comment]
I have also gotten this far with following the cmake instructions found here: [xmrig.com](https://xmrig.com/docs/miner/build/ubuntu).
I am also running 20.04 and would love to hear how you ended up solving this issue.

**Comment by penevd** [comment]
Not sure. I think I just dropped the whole project. Sorry I can't be of any help :(

**Comment by onemillionbucks** [comment]
same dude, I like to think I have a life outside setting up coding stuff
