### ISSUE TITLE
When will support for CUDA11.5 be released?

### ISSUE THREAD

**Issue by DarkAlchy** [xmrig/xmrig-cuda#133]
No matter what version I have tried (can't try the latest) this refuses to work with CUDA as it says there is a version mismatch.  I tried from 10 all the way to 11.4.  11.5 is latest.

**Comment by Spudz76** [comment]
What version of CUDA does your `nvidia-smi` say your driver offers?

**Comment by Spudz76** [comment]
Depending on what's saying version mismatch, note you have to have the latest xmrig itself along with the plugin.  You can't use 6.9.x with a newer plugin for example, none of them will work (API between xmrig and the plugin changed, not the API between the plugin and CUDA...)

**Comment by DarkAlchy** [comment]
11.5.0  and my Nvidia driver is 496.13.

**Comment by Spudz76** [comment]
Which GPU model?  Also an actual paste or screenshot of the actual error in context.

All of those should have worked fine.
