### ISSUE TITLE
xmrig-cuda fails in cuda_extra.cu 

### ISSUE THREAD

**Issue by charmparticle** [xmrig/xmrig-cuda#164]
Here's the output:

    charmparticle@laptop:~/Downloads/tabs/xmrig-6.17.0/xmrig-cuda$ make
    [  5%] Building NVCC (Device) object CMakeFiles/xmrig-cu.dir/src/xmrig-cu_generated_cuda_extra.cu.o
    xmrig-6.17.0/xmrig-cuda/src/cuda_extra.cu: In function ‘void cryptonight_extra_cpu_prepare(nvid_ctx*, uint32_t, const xmrig_cuda::Algorithm&)’:
    xmrig-6.17.0/xmrig-cuda/src/cuda_extra.cu:464:170: warning: passing argument 5 to ‘restrict’-qualified parameter aliases with argument 6 [-Wrestrict]
      464 |         CUDA_CHECK_KERNEL(ctx->device_id, cryptonight_extra_gpu_prepare<Algorithm::CN_0><<<grid, block >>>(wsize, ctx->d_input, ctx->inputlen, startNonce,
          |                                                                                                                                                                          ^                            
    xmrig-6.17.0/xmrig-cuda/src/cuda_extra.cu: In function ‘int cuda_get_deviceinfo(nvid_ctx*)’:
    xmrig-6.17.0/xmrig-cuda/src/cuda_extra.cu:624:26: warning: comparison of integer expressions of different signedness: ‘int’ and ‘const size_t’ {aka ‘const long unsigned int’} [-Wsign-compare]
      624 |         if (ctx->device_blocks > max_blocks) {
          |         ~~~~~~~~~~~~~~~~~^~~~~~~~~~~~
    [ 11%] Building NVCC (Device) object CMakeFiles/xmrig-cu.dir/src/AstroBWT/dero/xmrig-cu_generated_AstroBWT.cu.o
    /usr/include/c++/11/bits/std_function.h:435:145: error: parameter packs not expanded with ‘...’:
      435 |         function(_Functor&& __f)
          |                                                                                                                                                 ^ 
    /usr/include/c++/11/bits/std_function.h:435:145: note:         ‘_ArgTypes’
    /usr/include/c++/11/bits/std_function.h:530:146: error: parameter packs not expanded with ‘...’:
      530 |         operator=(_Functor&& __f)
          |                                                                                                                                                  ^ 
    /usr/include/c++/11/bits/std_function.h:530:146: note:         ‘_ArgTypes’
    CMake Error at xmrig-cu_generated_AstroBWT.cu.o.Release.cmake:280 (message):
      Error generating file
      xmrig-6.17.0/xmrig-cuda/CMakeFiles/xmrig-cu.dir/src/AstroBWT/dero/./xmrig-cu_generated_AstroBWT.cu.o
    
    
    make[2]: *** [CMakeFiles/xmrig-cu.dir/build.make:859: CMakeFiles/xmrig-cu.dir/src/AstroBWT/dero/xmrig-cu_generated_AstroBWT.cu.o] Error 1
    make[1]: *** [CMakeFiles/Makefile2:84: CMakeFiles/xmrig-cu.dir/all] Error 2
    make: *** [Makefile:91: all] Error 2

**Comment by Spudz76** [comment]
Bug with some versions of toolkit vs gcc 11.2 (see #154)

Use toolkit 11.6.1 or newer, or use gcc 10.x if you must use whichever older toolkit.
