### ISSUE TITLE
CUDA         disabled (no devices)

### ISSUE THREAD

**Issue by livelybug** [xmrig/xmrig-cuda#21]
Hello,
My machine is a bit old.

GPU: nVidia GEFORCE GT540M
OS: Windows 7 X64

config.json:
```
{
    "donate-level": 1,
    "cpu": false,
    "opencl": false,
    "cuda": true,
    "pools": [
        {
            "coin": "monero",
            "url": "pool.supportxmr.com:3333",
            "user": "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
            "keepalive": true,
            "tls": true
        }
    ]
}
```

Issue log:
```
E:\xmrig-5.0.1-msvc-cuda10_1-win64\xmrig-5.0.1>xmrig.exe
 * ABOUT        XMRig/5.0.1 MSVC/2017
 * LIBS         libuv/1.31.0 OpenSSL/1.1.1c hwloc/2.0.4
 * HUGE PAGES   permission granted
 * CPU          Intel(R) Core(TM) i7-2677M CPU @ 1.80GHz (1) x64 AES
                L2:0.5 MB L3:4.0 MB 2C/4T NUMA:1
 * DONATE       1%
 * ASSEMBLY     auto:intel
 * POOL #1      pool.supportxmr.com:3333 coin monero
 * COMMANDS     hashrate, pause, resume
 * OPENCL       disabled
 * CUDA         disabled (no devices)
```

CUDA and GPU driver are updated.
It seems that CUDA is not detected.
Thank you!

**Comment by Spudz76** [comment]
Must use CUDA 8 maximum for old Fermi based GPUs.
The precompiled release you've got is CUDA 10.1 for everything Maxwell or newer.

**Comment by Tesla-Nikola-2012** [comment]
How do you compile for CUDA 8?  I don't see source code for CUDA 8 in the downloads section.

My setup is Manjaro Linux with an Nvidia GTX 1060 3GB.

**Comment by username0012345** [comment]
Tesla-Nikola-2012

OS: Win 10
Miner: xmrig-6.6.2 
CPU: I3-8100 @ 3.60GHz
GPU: Nvida Geforce GT 730

So I was having the same problem as you but on a different OS; here is my fix.

Set one d/l : dll.

the link : https://xmrig.com/download/cuda 
The exact one I am using: Xmrig-cuda-6.5.0-cuda_9.0-win64.zip
                                       SHA256: d53430a1ff0de70f7b5d501f72b216d48d751320dd02598bd049f3af159a8fc0

Extract and place all the files inside the folder with the .EXE 
open your json and true cpu to false; cuda to true, algos in cuda to true from false

follow the basic set up in the json for wallet and password

save and execute.

Make sure to run as administrator, it will run to it's full potential. 

It should fix your problem.

**Comment by username0012345** [comment]
also don't forget v.2 is coming.... this coin as we know it will be evolved and starting fresh

**Comment by asw2012** [comment]
Hey all, I am having a tough time getting my GTX 570 to work on mining.  Which CUDA version to use and how to implement?  Thanks.  using XMRig

**Comment by Spudz76** [comment]
[CUDA Toolkit 8.0GA2](https://developer.nvidia.com/cuda-80-ga2-download-archive)

Build against it.
