### ISSUE TITLE
gcc-8: error: unrecognized command line option ‘-maes’

### ISSUE THREAD

**Issue by rnogy** [xmrig/xmrig-cuda#24]
hi, were unable to compile on arm aarch 64.

OS: Ubuntu 18.04.3 
CUDA: Cuda compilation tools, release 10.0, V10.0.326

~~-- The C compiler identification is GNU 7.4.0
-- The CXX compiler identification is Clang 6.0.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for _rotr
-- Looking for _rotr - not found
-- Looking for __builtin___clear_cache
-- Looking for __builtin___clear_cache - not found
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found CUDA: /usr/local/cuda (found suitable version "10.0", minimum required is "8.0") 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/husky/xmrig-cuda/build~~

husky@husky-desktop:~/xmrig-cuda/build$  make
[  8%] Building NVCC (Device) object CMakeFiles/xmrig-cu.dir/src/RandomX/wownero/xmrig-cu_generated_randomx_wownero.cu.o
gcc-8: error: unrecognized command line option ‘-maes’
CMake Error at xmrig-cu_generated_randomx_wownero.cu.o.Release.cmake:219 (message):
  Error generating
  /home/husky/xmrig-cuda/build/CMakeFiles/xmrig-cu.dir/src/RandomX/wownero/./xmrig-cu_generated_randomx_wownero.cu.o

CMakeFiles/xmrig-cu.dir/build.make:105: recipe for target 'CMakeFiles/xmrig-cu.dir/src/RandomX/wownero/xmrig-cu_generated_randomx_wownero.cu.o' failed
make[2]: *** [CMakeFiles/xmrig-cu.dir/src/RandomX/wownero/xmrig-cu_generated_randomx_wownero.cu.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/xmrig-cu.dir/all' failed
make[1]: *** [CMakeFiles/xmrig-cu.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by cdndcminer** [comment]
Do you have a guide on how to compile and its requirements? I havent found one and tried compiling on Ubuntu 16, 17 and 18 now. I have tried different versions of CUDA as well.

**Comment by xmrig** [comment]
@rnogy What hardware are you using and can you provide instructions how I can install CUDA on aarch64 to check this issue.
@cdndcminer https://xmrig.com/docs/miner/ubuntu-build CUDA tab

**Comment by rnogy** [comment]
@xmrig It is a Jetson Nano by Nvidia. Cuda came pre-installed with Jetpack.

**Comment by Spudz76** [comment]
There were reports of it working properly on Jetson boards in the past, new algos may have broken it.  Sounds like some flags are being set incorrectly in CMake.

**Comment by Spudz76** [comment]
Project is completely missing `cmake/cpu.cmake` which sets the `XMRIG_ARMv8` or `XMRIG_ARMv7` flags, and lacking those it will always assume it's on an x86 (which would have the `-maes` flag)

I think putting the `cmake/cpu.cmake` from regular xmrig and then adding it to `CMakeLists.txt` might get closer to working
[jetson-fixup.diff.txt](https://github.com/xmrig/xmrig-cuda/files/3980521/jetson-fixup.diff.txt)

**Comment by xmrig** [comment]
I added that file, ARM now should detected.
Thank you.
