### ISSUE TITLE
CUDA Error: thread #0 failed with error <randomx_prepare>:45 "out of memory"

### ISSUE THREAD

**Issue by zhoushijie163** [xmrig/xmrig-cuda#31]
thread #0 failed with error <randomx_prepare>:45 "out of memory"

**Comment by Spudz76** [comment]
I'd bet you're out of memory.  GPUs with less than 3GB can't RandomX.  Possibly with "dataset host" feature enabled but I've not had much luck with that either (and it's slow and a waste of watts even on a 2070 compared to if you setup a bunch of cheap Intel CPUs - kind of the point of RandomX in the first place)

**Comment by Braintelligence** [comment]
Yeah I have the same issue with a RTX 2080 Ti.
I don't think it should have such issues.
