### ISSUE TITLE
Watchdog Config Change VS Config First Run

### ISSUE THREAD

**Issue by doadin** [xmrig/xmrig-cuda#35]
Hello, so a few things.

```
    "cuda": {
        "enabled": true,
        "loader": null,
        "nvml": true,
        "bfactor": 12,
        "bsleep": 100,
        "cn/0": false,
        "cn-lite/0": false
    },
```
or 
```
    "cuda": {
        "enabled": true,
        "loader": null,
        "nvml": true,
        "cuda-bfactor": 12,
        "cuda-bsleep": 100,
        "cn/0": false,
        "cn-lite/0": false
    },
```
the bfactor nor bsleep seem to get set, how are we supposed to set these now?

Also with "watch": true

while running if i try to change cuda-bfactor it will change to disabled (no suitable configuration found)
even if I start it with "cuda-bfactor": 12 change to "cuda-bfactor": 10 then change back to "cuda-bfactor": 12 after the first change it says invalid even though the last change was the value it started fine with in the beginning.

**Comment by Spudz76** [comment]
I haven't had those work, ever.  I generate default then mass replace the two settings in each definition via editor.

**Comment by doadin** [comment]
so no fix?
