### ISSUE TITLE
Cuda - Failad load CUDA Plugmins

### ISSUE THREAD

**Issue by gikerus** [xmrig/xmrig-cuda#43]
Hey i have that issue.
Bat file:
C:\xmrig\xmrig.exe --donate-level 1 --cuda --cuda-loader=C:\xmrig\xmrig-cuda.dll  -o pool.minexmr.com:443 -u Pool --rig-id 515151 -k --tls  --threads=2

CMD:
 * ABOUT        XMRig/5.10.0 MSVC/2019
 * LIBS         libuv/1.34.0 OpenSSL/1.1.1d hwloc/2.1.0
 * HUGE PAGES   permission granted
 * 1GB PAGES    unavailable
 * CPU          AMD Athlon(tm) II X2 250 Processor (1) x64 -AES
                L2:2.0 MB L3:0.0 MB 2C/2T NUMA:1
 * MEMORY       1.9/7.7 GB (25%)
 * DONATE       1%
 * ASSEMBLY     auto:none
 * POOL #1      pool.minexmr.com:443 algo auto
 * COMMANDS     hashrate, pause, resume
 * OPENCL       disabled
 * **CUDA         disabled (failed to load CUDA plugin)**

I have on this file:
![image](https://user-images.githubusercontent.com/63429995/79924945-7211e880-8439-11ea-86c1-b1a91ac79c1f.png)

Driver Nvidia: 390.77
Cuda installed: 9.0 
Grafic cards: 2x nVIDIA GT 730

Do you need more information?
If not, can someone help me solve this problem?

**Comment by gikerus** [comment]
Someone can Help ?

**Comment by LesterCovax** [comment]
The highest supported CUDA version for GT 730 is v3.5.  You're basically trying to use a steam engine to run a sports car.
https://developer.nvidia.com/cuda-gpus

**Comment by gikerus** [comment]
> The highest supported CUDA version for GT 730 is v3.5. You're basically trying to use a steam engine to run a sports car.
> https://developer.nvidia.com/cuda-gpus

coś chyba źle zobaczyłeś bo najwyższe sterowniki jakie mam to 388.13 a one wspieraja CUDA 9.0

po przeinstalowaniu komputera i instlacji wszytskiego na nowo pojawiło się cos nowego, tylko czy jest to do obejścia ? ponizej podsyłam błąd

` * ABOUT        XMRig/5.11.3 MSVC/2019
 * LIBS         libuv/1.38.0 OpenSSL/1.1.1g hwloc/2.2.0
 * HUGE PAGES   permission granted
 * 1GB PAGES    unavailable
 * CPU          AMD Athlon(tm) II X2 250 Processor (1) x64 -AES
                L2:2.0 MB L3:0.0 MB 2C/2T NUMA:1
 * MEMORY       1.8/7.7 GB (24%)
 * DONATE       1%
 * ASSEMBLY     auto:none
 * POOL #1      pool.minexmr.com:443 algo auto
 * COMMANDS     hashrate, pause, resume
 * OPENCL       disabled
 * CUDA         9.0/9.1/6.2.0
 * NVML         9.388.13/388.13 press e for health report
 * CUDA GPU     #0 02:00.0 GeForce GT 730 901/2505 MHz smx:2 arch:35 mem:1698/2048 MB
 * CUDA GPU     #1 03:00.0 GeForce GT 730 1400/800 MHz smx:2 arch:21 mem:1689/2048 MB
[2020-06-12 22:08:37.583]  net  use pool pool.minexmr.com:443 TLSv1.3 94.130.164.163
[2020-06-12 22:08:37.584]  net  fingerprint (SHA-256): "f8cb85d6dc856748d376b48e6b87f90900b3f683fe505ef59de570296761d14b"
[2020-06-12 22:08:37.585]  net  new job from pool.minexmr.com:443 diff 175004 algo rx/0 height 2119215
[2020-06-12 22:08:37.585]  cpu  use argon2 implementation SSE2
[2020-06-12 22:08:37.586]  rx   init dataset algo rx/0 (2 threads) seed d10ce0939583c30c...
[2020-06-12 22:08:37.603]  rx   allocated 2336 MB (2080+256) huge pages 100% 1168/1168 +JIT (17 ms)
[2020-06-12 22:09:01.652]  rx   dataset ready (24048 ms)
[2020-06-12 22:09:01.656]  cpu  use profile  rx  (2 threads) scratchpad 2048 KB
[2020-06-12 22:09:01.695]  cpu  READY threads 2/2 (2) huge pages 100% 2/2 memory 4096 KB (36 ms)
[2020-06-12 22:09:01.726]  nv   use profile  rx  (2 threads) scratchpad 2048 KB
|  # | GPU |  BUS ID |    I |   T |   B | BF |  BS |  MEM | NAME
|  0 |   0 | 02:00.0 |  128 |  32 |   4 |  1 |  25 |  256 | GeForce GT 730
|  1 |   1 | 03:00.0 |  128 |  32 |   4 |  1 |  25 |  256 | GeForce GT 730
[2020-06-12 22:09:16.262]  nv   READY threads 2/2 (14394 ms)
**[2020-06-12 22:09:16.338]  nv   thread #1 failed with error <DatasetHost::reg>:50 "out of memory"
[2020-06-12 22:09:16.397]  nv   thread #0 failed with error <randomx_prepare>:36 "invalid argument"**
[2020-06-12 22:09:35.063]  net  new job from pool.minexmr.com:443 diff 175004 algo rx/0 height 2119215
[2020-06-12 22:09:40.444]  net  new job from pool.minexmr.com:443 diff 175004 algo rx/0 height 2119216
[2020-06-12 22:10:05.979]  nv   #0 02:00.0   0W 36C fan0:39%
[2020-06-12 22:10:06.029]  nv   #1 03:00.0   0W 36C fan0:35%`

**Comment by gikerus** [comment]
chodzi o te dwa błędy jest to do obejścia czy nie ?

**Comment by gikerus** [comment]
podsyłam kod jonson

> 
{
    "api": {
        "id": null,
        "worker-id": null
    },
    "http": {
        "enabled": false,
        "host": "127.0.0.1",
        "port": 0,
        "access-token": null,
        "restricted": true
    },
    "autosave": true,
    "background": false,
    "colors": true,
    "randomx": {
        "init": -1,
        "mode": "auto",
        "1gb-pages": false,
        "rdmsr": true,
        "wrmsr": true,
        "numa": true
    },
    "cpu": {
        "enabled": true,
        "huge-pages": true,
        "hw-aes": null,
        "priority": null,
        "memory-pool": false,
        "yield": true,
        "asm": true,
        "argon2-impl": null,
        "astrobwt-max-size": 550,
        "astrobwt-avx2": false,
        "argon2": [0, 1],
        "astrobwt": [0, 1],
        "cn": [
            [1, 0],
            [1, 1]
        ],
        "cn-heavy": [
            [1, -1]
        ],
        "cn-lite": [
            [1, 0],
            [1, 1]
        ],
        "cn-pico": [
            [2, 0],
            [2, 1]
        ],
        "rx": [0, 1],
        "rx/wow": [0, 1],
        "cn/0": false,
        "cn-lite/0": false,
        "rx/arq": "rx/wow",
        "rx/keva": "rx/wow"
    },
    "opencl": {
        "enabled": false,
        "cache": true,
        "loader": null,
        "platform": "AMD",
        "adl": true
    },
    "cuda": {
        "enabled": true,
        "loader": null,
        "nvml": true,
        "astrobwt": [
            {
                "index": 0,
                "threads": 32,
                "blocks": 5,
                "bfactor": 1,
                "bsleep": 25,
                "affinity": -1
            },
            {
                "index": 1,
                "threads": 32,
                "blocks": 5,
                "bfactor": 1,
                "bsleep": 25,
                "affinity": -1
            }
        ],
        "cn": [
            {
                "index": 0,
                "threads": 128,
                "blocks": 6,
                "bfactor": 1,
                "bsleep": 25,
                "affinity": -1
            },
            {
                "index": 1,
                "threads": 64,
                "blocks": 4,
                "bfactor": 1,
                "bsleep": 25,
                "affinity": -1
            }
        ],
        "cn-heavy": [
            {
                "index": 0,
                "threads": 64,
                "blocks": 6,
                "bfactor": 1,
                "bsleep": 25,
                "affinity": -1
            },
            {
                "index": 1,
                "threads": 40,
                "blocks": 4,
                "bfactor": 1,
                "bsleep": 25,
                "affinity": -1
            }
        ],
        "cn-lite": [
            {
                "index": 0,
                "threads": 128,
                "blocks": 6,
                "bfactor": 1,
                "bsleep": 25,
                "affinity": -1
            },
            {
                "index": 1,
                "threads": 64,
                "blocks": 4,
                "bfactor": 1,
                "bsleep": 25,
                "affinity": -1
            }
        ],
        "cn-pico": [
            {
                "index": 0,
                "threads": 4,
                "blocks": 16,
                "bfactor": 1,
                "bsleep": 25,
                "affinity": -1
            },
            {
                "index": 1,
                "threads": 4,
                "blocks": 16,
                "bfactor": 1,
                "bsleep": 25,
                "affinity": -1
            }
        ],
        "cn/2": [
            {
                "index": 0,
                "threads": 4,
                "blocks": 16,
                "bfactor": 1,
                "bsleep": 25,
                "affinity": -1
            },
            {
                "index": 1,
                "threads": 4,
                "blocks": 16,
                "bfactor": 1,
                "bsleep": 25,
                "affinity": -1
            }
        ],
        "rx": [
            {
                "index": 0,
                "threads": 32,
                "blocks": 4,
                "bfactor": 1,
                "bsleep": 25,
                "affinity": -1,
                "dataset_host": true
            },
            {
                "index": 1,
                "threads": 32,
                "blocks": 4,
                "bfactor": 1,
                "bsleep": 25,
                "affinity": -1,
                "dataset_host": true
            }
        ],
        "cn/0": false,
        "cn-lite/0": false
    },
    "donate-level": 1,
    "donate-over-proxy": 1,
    "log-file": null,
    "pools": [
        {
            "algo": null,
            "coin": null,
            "url": "pool.minexmr.com:443",
            "user": 
            "pass":
            "rig-id": "51",
            "nicehash": false,
            "keepalive": true,
            "enabled": true,
            "tls": true,
            "tls-fingerprint": null,
            "daemon": false,
            "socks5": null,
            "self-select": null
        }
    ],
    "print-time": 60,
    "health-print-time": 60,
    "retries": 5,
    "retry-pause": 5,
    "syslog": false,
    "tls": {
        "enabled": false,
        "protocols": null,
        "cert": null,
        "cert_key": null,
        "ciphers": null,
        "ciphersuites": null,
        "dhparam": null
    },
    "user-agent": null,
    "verbose": 0,
    "watch": true
}

>

**Comment by Spudz76** [comment]
Not enough memory for RandomX on both system RAM (1.8GB free) and GPU memory (256M total each)  Requires 2.25GB.

Second problem is arch 2x cards maximum CUDA Toolkit 8.0 so then the first card arch 3x is only that will work with CUDA 9.x.  With plugin on CUDA8.0 it should still work with 9.1 driver level you already have.  RandomX will not perform even if it did have enough memory.

**Comment by LesterCovax** [comment]
I meant to follow up after originally posting, but I may have mistaken CUDA
compute version with CUDA version (which are quite different)...so you can
prob ignore my comment.
