### ISSUE TITLE
Having trouble compiling the plugin for linux

### ISSUE THREAD

**Issue by JordanPlayz158** [xmrig/xmrig-cuda#61]
OS: Manjaro Linux x86_64
Host: MS-7A34 2.0
Kernel: 5.7.9-1-MANJARO
CPU: AMD Ryzen 7 3700X (16) @ 3.600GHz
GPU: NVIDIA GeForce GTX 1050 Ti
Memory: 5466MiB / 16026MiB
(Relevant info from neofetch)

I am having some issues trying to compile the plugin to get cuda to work, I have successfully done cmake without any issues but when it comes to make I get this
https://hastebin.com/zewiyazuto.m (I thought the output was a bit too long to put in a code block so I just decided to put it in hastebin, if you wish to have me put it in a code block in github I would be more than happy to do so)
If anyone can help me that would be much appreciated!

**Comment by xmrig** [comment]
gcc 10 is not listed as supported compiler even for CUDA 11.

refs:
* https://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html#introduction
* https://docs.nvidia.com/cuda/cuda-toolkit-release-notes/index.html#cuda-compiler-new-features

**Comment by JordanPlayz158** [comment]
Do you know how I would tell make to explicitly use gcc-8 or would it be easier to just override the gcc link that's going to 10 and put gcc-8 in it's place?

ls /usr/bin/gcc
gcc           gcc-ar        gcc-nm        gcc-ranlib    
gcc-8         gcc-ar-8      gcc-nm-8      gcc-ranlib-8

**Comment by xmrig** [comment]
You can use `cmake .. -DCMAKE_C_COMPILER=gcc-8 -DCMAKE_CXX_COMPILER=g++-8` with fresh start from scratch.
Thank you.

**Comment by JordanPlayz158** [comment]
Thank you, after doing the command you suggested it works like a charm, thanks for the help!

**Comment by JordanPlayz158** [comment]
After compiling and putting it in the same directory it doesn't seem to want to work

https://pastebin.com/ZPMmA09k

Here is my configuration file:

https://pastebin.com/zbMKc1ZK

Am I missing anything that is causing it not to work?

**Comment by xmrig** [comment]
`panthera` algorithm only supported by MoneroOcean fork, it not implemented for CUDA.
Thank you.

**Comment by JordanPlayz158** [comment]
Do all the pools in https://xmrig.com/wizard support CUDA or have algorithm's that support CUDA?

**Comment by xmrig** [comment]
All pools in the wizard except https://hashvault.pro/ is Monero pools, Monero uses the RandomX algorithm, it is supported for GPUs but not efficient by design.

Supported algorithms https://xmrig.com/docs/algorithms

Since you do not use the official miner list of algorithms is different.

**Comment by JordanPlayz158** [comment]
Ok thanks for everything I got it to work but gpu is only pushing 2k H/s and cpu is pushing 6k H/s so I will just stick to cpu mining rather than gpu because gpus typically have worse cooling than cpus.
