### ISSUE TITLE
CUDA disabled (no device)

### ISSUE THREAD

**Issue by skierliu** [xmrig/xmrig-cuda#79]
I am using the "xmrig-6.6.2" with "xmrig-cuda-6.5.0-cuda11_1-win64.zip", and my GPU is Nvidia GeForce RTX 2060, 6GB
But the CUDA plugin doesn't work, returning "CUDA disabled (no device)"

**Comment by BobbyBlock** [comment]
Did you figure out a solution in the end?

**Comment by skierliu** [comment]
> Did you figure out a solution in the end?

Yes, I updated my GPU driver to the latest version. 
But finally I gave up to use the CUDA plugin because the output is limited.
