### ISSUE TITLE
failed with error <reg>:53 "invalid argument"

### ISSUE THREAD

**Issue by Maanlake** [xmrig/xmrig-cuda#92]
build xmrig version on Nvidia Jetson Nano with CUDA plugin

got an <reg>:53 "invalid argument" at start

 * CUDA         10.2/10.2/6.5.0
 * NVML         disabled (failed to load NVML)
 * CUDA GPU     #0 00:00.0 NVIDIA Tegra X1 921/12 MHz smx:1 arch:53 mem:1108/1979 MB

|  # | GPU |  BUS ID | INTENSITY | THREADS | BLOCKS | BF |  BS | MEMORY | NAME
|  0 |   0 | 00:00.0 |        64 |      32 |      2 |  0 |   0 |    128 | NVIDIA Tegra X1
[2021-04-11 19:45:49.527]  cpu      READY threads 4/4 (4) huge pages 0% 0/4 memory 8192 KB (2 ms)
[2021-04-11 19:45:50.438]  nvidia   READY threads 1/1 (912 ms)
[2021-04-11 19:45:50.439]  nvidia   thread #0 failed with error <reg>:53 "invalid argument"

**Comment by Spudz76** [comment]
You've conveniently chopped out any info about which algo.  Guessing RandomX though which isn't a GPU algo and works worse the older the core is (yours is Maxwell, 53).  RandomX operates best (or at all) with Pascal or newer and even then is a waste of watts.  There is no algo that is excellent on both and also worth anything, and running a single instance for both CPU+GPU locksteps the algo between the two it will never be optimal.

Run CPU-only instance with CPU-algos, and another instance for GPU-only set for GPU-algos, and if you don't want to meddle with multiple coins use an autochanging pool that pays out everything in XMR.  Then you GPU can "mine XMR" without actually using an algo it's horrible at and wasting watts.  I use MoneroOcean, they have a fork of xmrig that allows autoswitching to the most lucrative coin whenever the prices change.

**Comment by Maanlake** [comment]
thank you very much for the answer. Yes I tried to mine xmr with random x. I used your tip and now also use moneroocean. Just have to turn off some GPU algo that could not be used because the memory of the jetson nano is too small.
